import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from '@/app/user/components/layout/Header';
import Footer from '@/app/user/components/layout/Footer';
import { AuthProvider } from '@/app/user/components/providers/AuthProvider';
import { MobileNavProvider } from '@/app/user/components/providers/MobileNavProvider';
import MobileNavDrawer from '@/app/user/components/layout/MobileNavDrawer';
import { ProfileMenuProvider } from '@/app/user/components/providers/ProfileMenuProvider';
import ProfileMenuLayer from '@/app/user/components/layout/ProfileMenuLayer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <MobileNavProvider>
        <ProfileMenuProvider>
          <div
            className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
          >
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
            <MobileNavDrawer />
            <ProfileMenuLayer />
          </div>
        </ProfileMenuProvider>
      </MobileNavProvider>
    </AuthProvider>
  );
}
